const TYPES = {
  ADD_PRODUCT: 'ADD_PRODUCT',
  GET_PRODUCTS: 'GET_PRODUCTS',
  GET_PRODUCT: 'GET_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',

  GET_BILLING: 'GET_BILLING',
  ADD_PRODUCT_TO_BILLING: 'ADD_PRODUCT_TO_BILLING',
}

export default TYPES;
