const TYPES = {
  ADD_PRODUCT: 'ADD_PRODUCT',
  ADD_PRODUCT_SUCCEEDED: 'ADD_PRODUCT_SUCCEEDED',
  ADD_PRODUCT_FAILED: 'ADD_PRODUCT_FAILED',

  GET_PRODUCTS: 'GET_PRODUCTS',
  GET_PRODUCTS_SUCCEEDED: 'GET_PRODUCTS_SUCCEEDED',
  GET_PRODUCTS_FAILED: 'GET_PRODUCTS_FAILED',

  GET_PRODUCT: 'GET_PRODUCT',

  UPDATE_PRODUCT: 'UPDATE_PRODUCT',

  GET_BILLING: 'GET_BILLING',

  ADD_PRODUCT_TO_BILLING: 'ADD_PRODUCT_TO_BILLING',
}

export default TYPES;
