const TYPES = {
  ADD_PRODUCT: 'ADD_PRODUCT',
  ADD_PRODUCT_SUCCEEDED: 'ADD_PRODUCT_SUCCEEDED',
  ADD_PRODUCT_FAILED: 'ADD_PRODUCT_FAILED',

  GET_PRODUCTS: 'GET_PRODUCTS',
  GET_PRODUCTS_SUCCEEDED: 'GET_PRODUCTS_SUCCEEDED',
  GET_PRODUCTS_FAILED: 'GET_PRODUCTS_FAILED',

  GET_PRODUCT: 'GET_PRODUCT',
  GET_PRODUCT_SUCCEEDED: 'GET_PRODUCT_SUCCEEDED',
  GET_PRODUCT_FAILED: 'GET_PRODUCT_FAILED',

  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  UPDATE_PRODUCT_SUCCEEDED: 'UPDATE_PRODUCT_SUCCEEDED',
  UPDATE_PRODUCT_FAILED: 'UPDATE_PRODUCT_FAILED',

  CLEAN_SELECTED_PRODUCT: 'CLEAN_SELECTED_PRODUCT',
  CLEAN_SELECTED_PRODUCTS: 'CLEAN_SELECTED_PRODUCTS',
  SET_SELECTED_PRODUCT: 'SET_SELECTED_PRODUCT',

  ADD_BILLING: 'ADD_BILLING',
  ADD_BILLING_SUCCEEDED: 'ADD_BILLING_SUCCEEDED',
  ADD_BILLING_FAILED: 'ADD_BILLING_FAILED',

  GET_BILLING: 'GET_BILLING',

  GET_BILLINGS: 'GET_BILLINGS',
  GET_BILLINGS_SUCCEEDED: 'GET_BILLINGS_SUCCEEDED',
  GET_BILLINGS_FAILED: 'GET_BILLINGS_FAILED',

  GET_LAST_BILLING: 'GET_LAST_BILLING',
  GET_LAST_BILLING_SUCCEEDED: 'GET_LAST_BILLING_SUCCEEDED',
  GET_LAST_BILLING_FAILED: 'GET_LAST_BILLING_FAILED',

  CLEAN_BILLING: 'CLEAN_BILLING',

  ADD_PRODUCT_TO_BILLING: 'ADD_PRODUCT_TO_BILLING',
  REMOVE_PRODUCT_FROM_BILLING: 'REMOVE_PRODUCT_FROM_BILLING',

  GET_SALES: 'SALES',
  GET_SALES_SUCCEEDED: 'SALES_SUCCEEDED',
  GET_SALES_FAILED: 'SALES_FAILED',

  GET_SALES_RESUME: 'SALES_RESUME',
  GET_SALES_RESUME_SUCCEEDED: 'SALES_RESUME_SUCCEEDED',
  GET_SALES_RESUME_FAILED: 'SALES_RESUME_FAILED'
}

export default TYPES;
